# -*- coding: utf-8 -*-
"""AI_Lab_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZ0QTbJ-ImWEejl-9VoFh0fB8Q742Epc
"""

#@title Activity # 1
def even_odd(a):
  if(a%2 == 0):
    print("the number is even")
  else:
    print("Number is odd")

a = int(input("Enter number: "))
even_odd(a)

# @title Activity # 2
sum = 0
a = int(input("Enter number or 0 to exit:"))
while(a!=0):
  sum = sum + a
  a = int(input("Enter number or 0 to exit:"))
print("Sum is",sum)

# @title Activity # 3
def is_prime(a):
  if (a%2 == 0):
    return True
  else:
    for i in range(2,int(a**(1/2))):
      if(a % i == 0):
        return True
    return False

a = int(input("Enter number: "))
if(is_prime(a) == True):
  print("Number is not prime")
else:
  print("Number is prime")

# @title Activity # 4
i = 0
sum = 0
while i<5:
  a = int(input("Enter number: "))
  sum += a
  i += 1
print("Sum of numbers is: ",sum)

#@title Activity # 5
sum = 0
for i in range(0,11):
  sum += i

print("sum of 0-10 is :",sum)

#@title Activity # 6
a = input("Write something positive: ")
print("You wrote: \n",a)

from random import randint
#@title Activity # 7
print("-----------Guess the number-------------")
a = randint(0,9)
b = input("Write your guess or type \'exit\' to abort: ")
guesses = 0
while(b != 'exit'):
  if int(b) > a:
    guesses += 1
    print("Guess is too high.\nTotal Guesses=",guesses)
  elif int(b) < a:
    guesses += 1
    print("Guess is too low.\nTotal Guesses=",guesses)
  else:
    print("Correct! The number was:",a)
    print("Guesses done :"guesses)
    guesses = 0

  b = input("Write your guess or type \'exit\' to abort: ")

 #end of loop